// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using migrationProject.Models;

namespace migrationProject.Migrations
{
    [DbContext(typeof(DbContextIndimnite))]
    [Migration("20210628202432_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("migrationProject.Models.Cadre", b =>
                {
                    b.Property<int>("IdCadre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CorpsIdcorps")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomComplet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idCorps")
                        .HasColumnType("int");

                    b.HasKey("IdCadre");

                    b.HasIndex("CorpsIdcorps");

                    b.ToTable("cadres");
                });

            modelBuilder.Entity("migrationProject.Models.Corps", b =>
                {
                    b.Property<int>("Idcorps")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Idcorps");

                    b.ToTable("corp");
                });

            modelBuilder.Entity("migrationProject.Models.Grades", b =>
                {
                    b.Property<int>("Idgrades")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CadreIdCadre")
                        .HasColumnType("int");

                    b.Property<int>("IdCadre")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomComplet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nomarabe")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Idgrades");

                    b.HasIndex("CadreIdCadre");

                    b.ToTable("grade");
                });

            modelBuilder.Entity("migrationProject.Models.OrdreMission", b =>
                {
                    b.Property<int>("idOrdremission")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdPers")
                        .HasColumnType("int");

                    b.Property<int?>("PersonnelIdPers")
                        .HasColumnType("int");

                    b.Property<int?>("Trajetid_trajet")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateArrivee")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDepart")
                        .HasColumnType("datetime2");

                    b.Property<int>("echlon")
                        .HasColumnType("int");

                    b.Property<bool>("etat")
                        .HasColumnType("bit");

                    b.Property<string>("grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("heureArrivee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("heureDepart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_trajet")
                        .HasColumnType("int");

                    b.Property<string>("matricule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("montant_total")
                        .HasColumnType("real");

                    b.Property<string>("moyenTransport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name_respo_mission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nombreCheuvaux")
                        .HasColumnType("int");

                    b.Property<string>("numero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("objetDepart")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idOrdremission");

                    b.HasIndex("PersonnelIdPers");

                    b.HasIndex("Trajetid_trajet");

                    b.ToTable("ordremission");
                });

            modelBuilder.Entity("migrationProject.Models.OrdrePayment", b =>
                {
                    b.Property<int>("IdOrdrePayment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdOrdreVirement")
                        .HasColumnType("int");

                    b.Property<int?>("OrdreMissionidOrdremission")
                        .HasColumnType("int");

                    b.Property<int>("idOrdremission")
                        .HasColumnType("int");

                    b.Property<double>("tatalKilo")
                        .HasColumnType("float");

                    b.Property<double>("totalDeplacement")
                        .HasColumnType("float");

                    b.HasKey("IdOrdrePayment");

                    b.HasIndex("OrdreMissionidOrdremission");

                    b.ToTable("ordrepaiement");
                });

            modelBuilder.Entity("migrationProject.Models.OrdreVirement", b =>
                {
                    b.Property<int>("IdOrdreVirement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdOrdrePayment")
                        .HasColumnType("int");

                    b.Property<int>("idAdmin")
                        .HasColumnType("int");

                    b.Property<string>("numero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numeroCompte")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdOrdreVirement");

                    b.ToTable("ordrevirement");
                });

            modelBuilder.Entity("migrationProject.Models.Parameter", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("valeur1")
                        .HasColumnType("int");

                    b.Property<int>("valeur2")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("parametre");
                });

            modelBuilder.Entity("migrationProject.Models.Parametre_image", b =>
                {
                    b.Property<int>("id_param_img")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("background")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("footer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("header")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_param_img");

                    b.ToTable("parametre_img");
                });

            modelBuilder.Entity("migrationProject.Models.Parametre_paiement", b =>
                {
                    b.Property<int>("id_param_paiement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Art")
                        .HasColumnType("int");

                    b.Property<int>("num1")
                        .HasColumnType("int");

                    b.Property<int>("num2")
                        .HasColumnType("int");

                    b.HasKey("id_param_paiement");

                    b.ToTable("param_paiement");
                });

            modelBuilder.Entity("migrationProject.Models.Parametre_voiture", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("nombre_cheveau_max")
                        .HasColumnType("int");

                    b.Property<int>("nombre_cheveau_min")
                        .HasColumnType("int");

                    b.Property<float>("prix_par_km")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("param_voiture");
                });

            modelBuilder.Entity("migrationProject.Models.Personnel", b =>
                {
                    b.Property<int>("IdPers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CadreIdCadre")
                        .HasColumnType("int");

                    b.Property<int?>("CorpsIdcorps")
                        .HasColumnType("int");

                    b.Property<string>("DRPP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateContract")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateEffetEchelon")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateEffetgrade")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateRecrutement")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateRecrutementENSA")
                        .HasColumnType("datetime2");

                    b.Property<int>("Echelle")
                        .HasColumnType("int");

                    b.Property<string>("Email1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GradesIdgrades")
                        .HasColumnType("int");

                    b.Property<string>("Gsm1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gsm2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCadre")
                        .HasColumnType("int");

                    b.Property<int>("Idcorps")
                        .HasColumnType("int");

                    b.Property<int>("Idgrades")
                        .HasColumnType("int");

                    b.Property<string>("Journauxrecherches")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lieuentiterecherches")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomCadre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomCorps")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomGrades")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NombreEnfant")
                        .HasColumnType("int");

                    b.Property<string>("Nomentiterecherches")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumContract")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceAffecte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SituationAdministratif")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SituationFamiliale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Société")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thematiquerecherches")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Typecontract")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeqEntiterecherches")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ville")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("anneediplome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("diplome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("echelon")
                        .HasColumnType("int");

                    b.Property<string>("ecolediplome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("liencv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomarabe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prenomarabe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("renouvelement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("show1")
                        .HasColumnType("bit");

                    b.Property<bool>("show2")
                        .HasColumnType("bit");

                    b.Property<string>("specialite")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPers");

                    b.HasIndex("CadreIdCadre");

                    b.HasIndex("CorpsIdcorps");

                    b.HasIndex("GradesIdgrades");

                    b.ToTable("personnels");
                });

            modelBuilder.Entity("migrationProject.Models.Trajet", b =>
                {
                    b.Property<int>("id_trajet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("distance")
                        .HasColumnType("int");

                    b.Property<string>("villeArrivee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("villeDepart")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_trajet");

                    b.ToTable("trajet");
                });

            modelBuilder.Entity("migrationProject.Models.Cadre", b =>
                {
                    b.HasOne("migrationProject.Models.Corps", null)
                        .WithMany("caders")
                        .HasForeignKey("CorpsIdcorps");
                });

            modelBuilder.Entity("migrationProject.Models.Grades", b =>
                {
                    b.HasOne("migrationProject.Models.Cadre", null)
                        .WithMany("Grades")
                        .HasForeignKey("CadreIdCadre");
                });

            modelBuilder.Entity("migrationProject.Models.OrdreMission", b =>
                {
                    b.HasOne("migrationProject.Models.Personnel", null)
                        .WithMany("ordermissions")
                        .HasForeignKey("PersonnelIdPers");

                    b.HasOne("migrationProject.Models.Trajet", null)
                        .WithMany("OrdreMissions")
                        .HasForeignKey("Trajetid_trajet");
                });

            modelBuilder.Entity("migrationProject.Models.OrdrePayment", b =>
                {
                    b.HasOne("migrationProject.Models.OrdreMission", null)
                        .WithMany("ordrePayment")
                        .HasForeignKey("OrdreMissionidOrdremission");
                });

            modelBuilder.Entity("migrationProject.Models.Personnel", b =>
                {
                    b.HasOne("migrationProject.Models.Cadre", null)
                        .WithMany("Personnels")
                        .HasForeignKey("CadreIdCadre");

                    b.HasOne("migrationProject.Models.Corps", null)
                        .WithMany("Personnels")
                        .HasForeignKey("CorpsIdcorps");

                    b.HasOne("migrationProject.Models.Grades", null)
                        .WithMany("Personnels")
                        .HasForeignKey("GradesIdgrades");
                });

            modelBuilder.Entity("migrationProject.Models.Cadre", b =>
                {
                    b.Navigation("Grades");

                    b.Navigation("Personnels");
                });

            modelBuilder.Entity("migrationProject.Models.Corps", b =>
                {
                    b.Navigation("caders");

                    b.Navigation("Personnels");
                });

            modelBuilder.Entity("migrationProject.Models.Grades", b =>
                {
                    b.Navigation("Personnels");
                });

            modelBuilder.Entity("migrationProject.Models.OrdreMission", b =>
                {
                    b.Navigation("ordrePayment");
                });

            modelBuilder.Entity("migrationProject.Models.Personnel", b =>
                {
                    b.Navigation("ordermissions");
                });

            modelBuilder.Entity("migrationProject.Models.Trajet", b =>
                {
                    b.Navigation("OrdreMissions");
                });
#pragma warning restore 612, 618
        }
    }
}
